import Navbar from "@/components/header/navbar";
import { Inter, Flow_Circular } from "next/font/google";
import "../globals.css";

import { Providers } from "@/store/Provider";
import ClientBottomPlayer from "@/components/music/client-bottom-player";
import { ClientMediaElementProviders } from "@/contexts/ClientMediaElementContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <ClientMediaElementProviders>
        <html lang="en">
          <body className={(inter.className, "bg-primaryBg")}>
            <Navbar />
            {children}
            <ClientBottomPlayer></ClientBottomPlayer>
          </body>
        </html>
      </ClientMediaElementProviders>
    </Providers>
  );
}
